// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ToggleOnOff_Animation( lv_obj_t *TargetObject, int delay);
void twist_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Container2;
lv_obj_t *ui_BatBarLeft;
lv_obj_t *ui_BatBarCenter;
lv_obj_t *ui_BatBarRight;
lv_obj_t *ui_ConnectBuzzersLabel;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
void ui_event_Panel2( lv_event_t * e);
lv_obj_t *ui_Panel2;
void ui_event_SpeedSlider( lv_event_t * e);
lv_obj_t *ui_SpeedSlider;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label2;
void ui_event_TapperOnOffBtn( lv_event_t * e);
lv_obj_t *ui_TapperOnOffBtn;
lv_obj_t *ui_TapperOnOffLabel;
lv_obj_t *ui_Container1;
lv_obj_t *ui_BatLabel;
lv_obj_t *ui_BatLeftLabel;
lv_obj_t *ui_BatRightLabel;
lv_obj_t *ui_Image2;
lv_obj_t *ui_SpeedLabel;
lv_obj_t *ui_SliderValueLabel;
lv_obj_t *ui_ConnectBuzzersLabel1;
lv_obj_t *ui_isCheckBoxLabel;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t *ui_Screen3;
void ui_event_Panel3( lv_event_t * e);
lv_obj_t *ui_Panel3;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label3;
lv_obj_t *ui_BuzzCheck;
lv_obj_t *ui_BuzzOnOffLabel;
lv_obj_t *ui_LightCheck;
lv_obj_t *ui_SoundCheck;
lv_obj_t *ui_Image3;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t *ui_Screen4;
void ui_event_Panel4( lv_event_t * e);
lv_obj_t *ui_Panel4;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
void ui_event_Button9( lv_event_t * e);
lv_obj_t *ui_Button9;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Container4;
lv_obj_t *ui_BuzzDropdownContainer;
lv_obj_t *ui_BuzzPower;
lv_obj_t *ui_BuzzLenght;
lv_obj_t *ui_LiightDropdownContainer;
lv_obj_t *ui_LightIntensity;
lv_obj_t *ui_LightLenght;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label15;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
void ui_event_Panel5( lv_event_t * e);
lv_obj_t *ui_Panel5;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;
void ui_event_Button10( lv_event_t * e);
lv_obj_t *ui_Button10;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Image5;
lv_obj_t *ui_SoundDropdownContainer;
lv_obj_t *ui_SoundVolume;
lv_obj_t *ui_SoundLenght;
lv_obj_t *ui_Label12;


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t *ui_Screen6;
void ui_event_Panel6( lv_event_t * e);
lv_obj_t *ui_Panel6;
void ui_event_Button11( lv_event_t * e);
lv_obj_t *ui_Button11;
void ui_event_Button12( lv_event_t * e);
lv_obj_t *ui_Button12;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Image6;
lv_obj_t *ui_SliderBrightness;
lv_obj_t *ui_Label10;


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t *ui_Screen7;
void ui_event_Panel7( lv_event_t * e);
lv_obj_t *ui_Panel7;
void ui_event_Button13( lv_event_t * e);
lv_obj_t *ui_Button13;
void ui_event_Button14( lv_event_t * e);
lv_obj_t *ui_Button14;
lv_obj_t *ui_Image7;
lv_obj_t *ui_Label16;
lv_obj_t *ui_PressureDropdownContainer;
lv_obj_t *ui_PressureDropdown_2;
lv_obj_t *ui_PressureDropdown_1;
lv_obj_t *ui_PressureCheck;
lv_obj_t *ui_Container6;
lv_obj_t *ui_PressureIntensitySlider;
lv_obj_t *ui_PressureSensitivitySlider;
lv_obj_t *ui_PressureIntensitySliderLabel;
lv_obj_t *ui_PressureSensitivitySliderLabel;


// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t *ui_Screen8;
void ui_event_Button8( lv_event_t * e);
lv_obj_t *ui_Button8;
void ui_event_Button15( lv_event_t * e);
lv_obj_t *ui_Button15;
lv_obj_t *ui_Label5;
void ui_event_Panel1( lv_event_t * e);
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Container5;
lv_obj_t *ui_BuzzIntensitySlider;
lv_obj_t *ui_BuzzIntensitySliderLabel;
lv_obj_t *ui_BuzzLenghtSlider;
lv_obj_t *ui_BuzzLenghtSliderLabel;
lv_obj_t *ui_LightIntensitySlider;
lv_obj_t *ui_LightIntensitySliderLabel;
lv_obj_t *ui_LightColourSlider;
lv_obj_t *ui_LightColourSliderLabel;
lv_obj_t *ui_SoundIntensitySlider;
lv_obj_t *ui_SoundLenghtSliderLabel;
lv_obj_t *ui_SoundLenghtSlider;
lv_obj_t *ui_SoundIntensitySliderLabel;


// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
lv_obj_t *ui_Screen9;
lv_obj_t *ui_Colorwheel2;


// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
lv_obj_t *ui_Screen10;
lv_obj_t *ui_Colorwheel1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_slide[1] = {&ui_img_slide1_png};
const lv_img_dsc_t *ui_imgset_1605022667[1] = {&ui_img_1751633538};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ToggleOnOff_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 10 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void twist_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 100 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_Panel2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
}
void ui_event_SpeedSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      _ui_slider_set_text_value( ui_SliderValueLabel, target, "", "");
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_slider_set_text_value( ui_SliderValueLabel, target, "", "");
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen2);
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen2);
}
}
void ui_event_TapperOnOffBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TapperStartStopButtonFunction( e );
}
}
void ui_event_Panel3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen2_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen8_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
}
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
}
void ui_event_Panel4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen4);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
      _ui_screen_delete( &ui_Screen4);
}
}
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen4);
}
}
void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
      _ui_screen_delete( &ui_Screen4);
}
}
void ui_event_Panel5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen4_screen_init);
      _ui_screen_delete( &ui_Screen5);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen6_screen_init);
      _ui_screen_delete( &ui_Screen5);
}
}
void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
      _ui_screen_delete( &ui_Screen5);
}
}
void ui_event_Button10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
      _ui_screen_delete( &ui_Screen5);
}
}
void ui_event_Panel6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen7_screen_init);
      _ui_screen_delete( &ui_Screen6);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen6);
}
}
void ui_event_Button11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
      _ui_screen_delete( &ui_Screen6);
}
}
void ui_event_Button12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
      _ui_screen_delete( &ui_Screen6);
}
}
void ui_event_Panel7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen8_screen_init);
      _ui_screen_delete( &ui_Screen7);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen6_screen_init);
      _ui_screen_delete( &ui_Screen7);
}
}
void ui_event_Button13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
      _ui_screen_delete( &ui_Screen7);
}
}
void ui_event_Button14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
      _ui_screen_delete( &ui_Screen7);
}
}
void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
      _ui_screen_delete( &ui_Screen8);
}
}
void ui_event_Button15( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen8);
}
}
void ui_event_Panel1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen8);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen7_screen_init);
      _ui_screen_delete( &ui_Screen8);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui_Screen5_screen_init();
ui_Screen6_screen_init();
ui_Screen7_screen_init();
ui_Screen8_screen_init();
ui_Screen9_screen_init();
ui_Screen10_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
