// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x8F9ABF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel4, 240);
lv_obj_set_height( ui_Panel4, 89);
lv_obj_set_x( ui_Panel4, -2 );
lv_obj_set_y( ui_Panel4, 217 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xACB2CD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button6, 64);
lv_obj_set_height( ui_Button6, 74);
lv_obj_set_x( ui_Button6, -77 );
lv_obj_set_y( ui_Button6, 217 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button9 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button9, 64);
lv_obj_set_height( ui_Button9, 74);
lv_obj_set_x( ui_Button9, 70 );
lv_obj_set_y( ui_Button9, 217 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 108 );
lv_obj_set_y( ui_Label4, -256 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"4");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_Screen4);
lv_img_set_src(ui_Image4, &ui_img_1567796331);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image4, -4 );
lv_obj_set_y( ui_Image4, 219 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,500);

ui_Container4 = lv_obj_create(ui_Screen4);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 231);
lv_obj_set_height( ui_Container4, 446);
lv_obj_set_x( ui_Container4, -3 );
lv_obj_set_y( ui_Container4, -33 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BuzzDropdownContainer = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_BuzzDropdownContainer);
lv_obj_set_width( ui_BuzzDropdownContainer, 226);
lv_obj_set_height( ui_BuzzDropdownContainer, 167);
lv_obj_set_x( ui_BuzzDropdownContainer, 5 );
lv_obj_set_y( ui_BuzzDropdownContainer, -109 );
lv_obj_set_align( ui_BuzzDropdownContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BuzzDropdownContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BuzzDropdownContainer, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BuzzDropdownContainer, lv_color_hex(0xF48497), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzDropdownContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BuzzDropdownContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzDropdownContainer, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzPower = lv_dropdown_create(ui_BuzzDropdownContainer);
lv_dropdown_set_options( ui_BuzzPower, "Power 1\nPower 2\nPower 3\nPower 4" );
lv_obj_set_width( ui_BuzzPower, 180);
lv_obj_set_height( ui_BuzzPower, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BuzzPower, 0 );
lv_obj_set_y( ui_BuzzPower, -41 );
lv_obj_set_align( ui_BuzzPower, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BuzzPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_BuzzPower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BuzzPower, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BuzzPower, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BuzzPower, lv_color_hex(0x5BC398), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzPower, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_BuzzPower, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_BuzzPower, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_BuzzPower), lv_color_hex(0xF6859C),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_BuzzPower), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_BuzzPower), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzLenght = lv_dropdown_create(ui_BuzzDropdownContainer);
lv_dropdown_set_options( ui_BuzzLenght, "Lenght 1\nLenght 2\nLength 3\nLenght 4" );
lv_obj_set_width( ui_BuzzLenght, 180);
lv_obj_set_height( ui_BuzzLenght, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BuzzLenght, 0 );
lv_obj_set_y( ui_BuzzLenght, 39 );
lv_obj_set_align( ui_BuzzLenght, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BuzzLenght, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_BuzzLenght, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BuzzLenght, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BuzzLenght, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BuzzLenght, lv_color_hex(0x5BC398), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzLenght, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_BuzzLenght, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_BuzzLenght, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_BuzzLenght), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_BuzzLenght), &lv_font_montserrat_20,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_LiightDropdownContainer = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_LiightDropdownContainer);
lv_obj_set_width( ui_LiightDropdownContainer, 228);
lv_obj_set_height( ui_LiightDropdownContainer, 175);
lv_obj_set_x( ui_LiightDropdownContainer, 6 );
lv_obj_set_y( ui_LiightDropdownContainer, 109 );
lv_obj_set_align( ui_LiightDropdownContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_LiightDropdownContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LiightDropdownContainer, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LiightDropdownContainer, lv_color_hex(0xF0FC81), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LiightDropdownContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LiightDropdownContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LiightDropdownContainer, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightIntensity = lv_dropdown_create(ui_LiightDropdownContainer);
lv_dropdown_set_options( ui_LightIntensity, "Bright 1\nBright 2\nBright 3\nBright 4" );
lv_obj_set_width( ui_LightIntensity, 180);
lv_obj_set_height( ui_LightIntensity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightIntensity, 0 );
lv_obj_set_y( ui_LightIntensity, -40 );
lv_obj_set_align( ui_LightIntensity, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LightIntensity, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_LightIntensity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightIntensity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightIntensity, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightIntensity, lv_color_hex(0x5BC398), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightIntensity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_LightIntensity, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_LightIntensity, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_LightIntensity), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_LightIntensity), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_LightIntensity), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightLenght = lv_dropdown_create(ui_LiightDropdownContainer);
lv_dropdown_set_options( ui_LightLenght, "RED\nGREEN\nBLUE\nWHITE" );
lv_obj_set_width( ui_LightLenght, 180);
lv_obj_set_height( ui_LightLenght, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightLenght, 0 );
lv_obj_set_y( ui_LightLenght, 41 );
lv_obj_set_align( ui_LightLenght, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LightLenght, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_LightLenght, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightLenght, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightLenght, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightLenght, lv_color_hex(0x5BC398), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightLenght, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_LightLenght, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_LightLenght), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_LightLenght), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_LightLenght), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 180
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Label11, -3 );
lv_obj_set_y( ui_Label11, -210 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Buzz");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x080101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 192
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Label15, -4 );
lv_obj_set_y( ui_Label15, 2 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Light");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x080101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
