// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x8F9ABF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel3, 240);
lv_obj_set_height( ui_Panel3, 89);
lv_obj_set_x( ui_Panel3, -2 );
lv_obj_set_y( ui_Panel3, 217 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xACB2CD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button5, 60);
lv_obj_set_height( ui_Button5, 76);
lv_obj_set_x( ui_Button5, 78 );
lv_obj_set_y( ui_Button5, 221 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button4 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button4, 59);
lv_obj_set_height( ui_Button4, 74);
lv_obj_set_x( ui_Button4, -84 );
lv_obj_set_y( ui_Button4, 221 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 112 );
lv_obj_set_y( ui_Label3, -256 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"3");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzCheck = lv_checkbox_create(ui_Screen3);
lv_checkbox_set_text(ui_BuzzCheck,"Buzz");
lv_obj_set_width( ui_BuzzCheck, 200);
lv_obj_set_height( ui_BuzzCheck, 100);
lv_obj_set_x( ui_BuzzCheck, -12 );
lv_obj_set_y( ui_BuzzCheck, -197 );
lv_obj_set_align( ui_BuzzCheck, LV_ALIGN_CENTER );
lv_obj_add_state( ui_BuzzCheck, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_BuzzCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_align(ui_BuzzCheck, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BuzzCheck, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BuzzCheck, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BuzzCheck, lv_color_hex(0xF6859C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzCheck, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BuzzCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzCheck, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BuzzCheck, 40, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BuzzCheck, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BuzzCheck, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BuzzCheck, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BuzzCheck, lv_color_hex(0xF6859C), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_BuzzCheck, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_grad_color(ui_BuzzCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_grad_dir(ui_BuzzCheck, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_BuzzOnOffLabel = lv_label_create(ui_BuzzCheck);
lv_obj_set_width( ui_BuzzOnOffLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BuzzOnOffLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BuzzOnOffLabel, -39 );
lv_obj_set_y( ui_BuzzOnOffLabel, -28 );
lv_obj_set_align( ui_BuzzOnOffLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BuzzOnOffLabel,"Off");
lv_obj_add_flag( ui_BuzzOnOffLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_BuzzOnOffLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BuzzOnOffLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BuzzOnOffLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightCheck = lv_checkbox_create(ui_Screen3);
lv_checkbox_set_text(ui_LightCheck,"Light");
lv_obj_set_width( ui_LightCheck, 199);
lv_obj_set_height( ui_LightCheck, 100);
lv_obj_set_x( ui_LightCheck, -13 );
lv_obj_set_y( ui_LightCheck, -65 );
lv_obj_set_align( ui_LightCheck, LV_ALIGN_CENTER );
lv_obj_add_state( ui_LightCheck, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_LightCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_LightCheck, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_LightCheck, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightCheck, lv_color_hex(0xF6FF83), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightCheck, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LightCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightCheck, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LightCheck, 40, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LightCheck, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LightCheck, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LightCheck, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightCheck, lv_color_hex(0xF6FF83), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LightCheck, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_grad_color(ui_LightCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_grad_dir(ui_LightCheck, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_SoundCheck = lv_checkbox_create(ui_Screen3);
lv_checkbox_set_text(ui_SoundCheck,"Sound");
lv_obj_set_width( ui_SoundCheck, 221);
lv_obj_set_height( ui_SoundCheck, 93);
lv_obj_set_x( ui_SoundCheck, -2 );
lv_obj_set_y( ui_SoundCheck, 67 );
lv_obj_set_align( ui_SoundCheck, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SoundCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_SoundCheck, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SoundCheck, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SoundCheck, lv_color_hex(0x3959F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundCheck, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SoundCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundCheck, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SoundCheck, 40, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SoundCheck, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SoundCheck, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SoundCheck, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SoundCheck, lv_color_hex(0x3959F6), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SoundCheck, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_grad_color(ui_SoundCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_grad_dir(ui_SoundCheck, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_Image3 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_Image3, &ui_img_1567796331);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, -4 );
lv_obj_set_y( ui_Image3, 219 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,500);

lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
