// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_slide1_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 111 );
lv_obj_set_y( ui_Label1, -256 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"1");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container2 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 240);
lv_obj_set_height( ui_Container2, 21);
lv_obj_set_x( ui_Container2, -1 );
lv_obj_set_y( ui_Container2, 0 );
lv_obj_set_align( ui_Container2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatBarLeft = lv_bar_create(ui_Container2);
lv_bar_set_value(ui_BatBarLeft,30,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BatBarLeft, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BatBarLeft, 33);
lv_obj_set_height( ui_BatBarLeft, 12);
lv_obj_set_x( ui_BatBarLeft, 5 );
lv_obj_set_y( ui_BatBarLeft, 0 );
lv_obj_set_align( ui_BatBarLeft, LV_ALIGN_LEFT_MID );
lv_obj_set_style_bg_color(ui_BatBarLeft, lv_color_hex(0xF84138), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatBarLeft, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BatBarLeft, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatBarLeft, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_BatBarCenter = lv_bar_create(ui_Container2);
lv_bar_set_value(ui_BatBarCenter,30,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BatBarCenter, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BatBarCenter, 33);
lv_obj_set_height( ui_BatBarCenter, 12);
lv_obj_set_align( ui_BatBarCenter, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_BatBarCenter, lv_color_hex(0xF84138), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatBarCenter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BatBarCenter, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatBarCenter, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_BatBarRight = lv_bar_create(ui_Container2);
lv_bar_set_value(ui_BatBarRight,30,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BatBarRight, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BatBarRight, 33);
lv_obj_set_height( ui_BatBarRight, 12);
lv_obj_set_x( ui_BatBarRight, -13 );
lv_obj_set_y( ui_BatBarRight, 0 );
lv_obj_set_align( ui_BatBarRight, LV_ALIGN_RIGHT_MID );
lv_obj_set_style_bg_color(ui_BatBarRight, lv_color_hex(0xF84138), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatBarRight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BatBarRight, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatBarRight, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_ConnectBuzzersLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ConnectBuzzersLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ConnectBuzzersLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ConnectBuzzersLabel, -3 );
lv_obj_set_y( ui_ConnectBuzzersLabel, -226 );
lv_obj_set_align( ui_ConnectBuzzersLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ConnectBuzzersLabel,"ConnectBuzzersLabel");

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
