// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen8_screen_init(void)
{
ui_Screen8 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen8, lv_color_hex(0x8F9ABF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen8, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button8 = lv_btn_create(ui_Screen8);
lv_obj_set_width( ui_Button8, 64);
lv_obj_set_height( ui_Button8, 74);
lv_obj_set_x( ui_Button8, -75 );
lv_obj_set_y( ui_Button8, 125 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button15 = lv_btn_create(ui_Screen8);
lv_obj_set_width( ui_Button15, 64);
lv_obj_set_height( ui_Button15, 74);
lv_obj_set_x( ui_Button15, 70 );
lv_obj_set_y( ui_Button15, 126 );
lv_obj_set_align( ui_Button15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button15, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Screen8);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 108 );
lv_obj_set_y( ui_Label5, -256 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"8");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen8);
lv_obj_set_width( ui_Panel1, 240);
lv_obj_set_height( ui_Panel1, 89);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, 216 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xACB2CD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Screen8);
lv_img_set_src(ui_Image8, &ui_img_1567796331);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, -4 );
lv_obj_set_y( ui_Image8, 219 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image8,500);

ui_Container5 = lv_obj_create(ui_Screen8);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 228);
lv_obj_set_height( ui_Container5, 424);
lv_obj_set_x( ui_Container5, 0 );
lv_obj_set_y( ui_Container5, -46 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BuzzIntensitySlider = lv_slider_create(ui_Container5);
lv_slider_set_range(ui_BuzzIntensitySlider, 5,250);
lv_slider_set_value( ui_BuzzIntensitySlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_BuzzIntensitySlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_BuzzIntensitySlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BuzzIntensitySlider, 200);
lv_obj_set_height( ui_BuzzIntensitySlider, 30);
lv_obj_set_x( ui_BuzzIntensitySlider, 0 );
lv_obj_set_y( ui_BuzzIntensitySlider, -193 );
lv_obj_set_align( ui_BuzzIntensitySlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_BuzzIntensitySlider, lv_color_hex(0xF6859C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzIntensitySlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BuzzIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BuzzIntensitySlider, lv_color_hex(0xF6859C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzIntensitySlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BuzzIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_BuzzIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_BuzzIntensitySliderLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_BuzzIntensitySliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BuzzIntensitySliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BuzzIntensitySliderLabel, 0 );
lv_obj_set_y( ui_BuzzIntensitySliderLabel, -166 );
lv_obj_set_align( ui_BuzzIntensitySliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BuzzIntensitySliderLabel,"Buzz Intensity");
lv_obj_set_style_text_color(ui_BuzzIntensitySliderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BuzzIntensitySliderLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzLenghtSlider = lv_slider_create(ui_Container5);
lv_slider_set_range(ui_BuzzLenghtSlider, 1,4);
lv_slider_set_value( ui_BuzzLenghtSlider, 2, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_BuzzLenghtSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_BuzzLenghtSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BuzzLenghtSlider, 200);
lv_obj_set_height( ui_BuzzLenghtSlider, 30);
lv_obj_set_x( ui_BuzzLenghtSlider, 0 );
lv_obj_set_y( ui_BuzzLenghtSlider, -130 );
lv_obj_set_align( ui_BuzzLenghtSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_BuzzLenghtSlider, lv_color_hex(0xF6859C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzLenghtSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BuzzLenghtSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzLenghtSlider, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BuzzLenghtSlider, lv_color_hex(0xF6859C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BuzzLenghtSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BuzzLenghtSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzLenghtSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_BuzzLenghtSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BuzzLenghtSlider, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_BuzzLenghtSliderLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_BuzzLenghtSliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BuzzLenghtSliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BuzzLenghtSliderLabel, 0 );
lv_obj_set_y( ui_BuzzLenghtSliderLabel, -99 );
lv_obj_set_align( ui_BuzzLenghtSliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BuzzLenghtSliderLabel,"Buzz Length");
lv_obj_set_style_text_color(ui_BuzzLenghtSliderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BuzzLenghtSliderLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightIntensitySlider = lv_slider_create(ui_Container5);
lv_slider_set_range(ui_LightIntensitySlider, 5,250);
lv_slider_set_value( ui_LightIntensitySlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LightIntensitySlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LightIntensitySlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LightIntensitySlider, 200);
lv_obj_set_height( ui_LightIntensitySlider, 30);
lv_obj_set_x( ui_LightIntensitySlider, 0 );
lv_obj_set_y( ui_LightIntensitySlider, -54 );
lv_obj_set_align( ui_LightIntensitySlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_LightIntensitySlider, lv_color_hex(0xF6FF83), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightIntensitySlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LightIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LightIntensitySlider, lv_color_hex(0xF6FF83), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightIntensitySlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LightIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_LightIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LightIntensitySliderLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_LightIntensitySliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightIntensitySliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightIntensitySliderLabel, 1 );
lv_obj_set_y( ui_LightIntensitySliderLabel, -23 );
lv_obj_set_align( ui_LightIntensitySliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightIntensitySliderLabel,"Light Intensity");
lv_obj_set_style_text_color(ui_LightIntensitySliderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightIntensitySliderLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightColourSlider = lv_slider_create(ui_Container5);
lv_slider_set_range(ui_LightColourSlider, 1,4);
lv_slider_set_value( ui_LightColourSlider, 3, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LightColourSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LightColourSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LightColourSlider, 200);
lv_obj_set_height( ui_LightColourSlider, 30);
lv_obj_set_x( ui_LightColourSlider, 0 );
lv_obj_set_y( ui_LightColourSlider, 13 );
lv_obj_set_align( ui_LightColourSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_LightColourSlider, lv_color_hex(0xF6FF83), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightColourSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LightColourSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightColourSlider, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LightColourSlider, lv_color_hex(0xF6FF83), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightColourSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LightColourSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightColourSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_LightColourSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_LightColourSlider, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LightColourSliderLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_LightColourSliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightColourSliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightColourSliderLabel, 0 );
lv_obj_set_y( ui_LightColourSliderLabel, 41 );
lv_obj_set_align( ui_LightColourSliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightColourSliderLabel,"LightColour ");
lv_obj_set_style_text_color(ui_LightColourSliderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightColourSliderLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SoundIntensitySlider = lv_slider_create(ui_Container5);
lv_slider_set_range(ui_SoundIntensitySlider, 5,250);
lv_slider_set_value( ui_SoundIntensitySlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SoundIntensitySlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SoundIntensitySlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SoundIntensitySlider, 200);
lv_obj_set_height( ui_SoundIntensitySlider, 30);
lv_obj_set_x( ui_SoundIntensitySlider, 0 );
lv_obj_set_y( ui_SoundIntensitySlider, 85 );
lv_obj_set_align( ui_SoundIntensitySlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SoundIntensitySlider, lv_color_hex(0x3959F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundIntensitySlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SoundIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SoundIntensitySlider, lv_color_hex(0x3959F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundIntensitySlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SoundIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_SoundIntensitySlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundIntensitySlider, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SoundLenghtSliderLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_SoundLenghtSliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SoundLenghtSliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SoundLenghtSliderLabel, -12 );
lv_obj_set_y( ui_SoundLenghtSliderLabel, 175 );
lv_obj_set_align( ui_SoundLenghtSliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SoundLenghtSliderLabel,"Sound Lenght");
lv_obj_set_style_text_color(ui_SoundLenghtSliderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SoundLenghtSliderLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SoundLenghtSlider = lv_slider_create(ui_Container5);
lv_slider_set_range(ui_SoundLenghtSlider, 1,4);
lv_slider_set_value( ui_SoundLenghtSlider, 2, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SoundLenghtSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SoundLenghtSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SoundLenghtSlider, 200);
lv_obj_set_height( ui_SoundLenghtSlider, 30);
lv_obj_set_x( ui_SoundLenghtSlider, 0 );
lv_obj_set_y( ui_SoundLenghtSlider, 146 );
lv_obj_set_align( ui_SoundLenghtSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SoundLenghtSlider, lv_color_hex(0x3959F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundLenghtSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SoundLenghtSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundLenghtSlider, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SoundLenghtSlider, lv_color_hex(0x3959F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundLenghtSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SoundLenghtSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundLenghtSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_SoundLenghtSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SoundLenghtSlider, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SoundIntensitySliderLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_SoundIntensitySliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SoundIntensitySliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SoundIntensitySliderLabel, 0 );
lv_obj_set_y( ui_SoundIntensitySliderLabel, 112 );
lv_obj_set_align( ui_SoundIntensitySliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SoundIntensitySliderLabel,"Sound Intensity");
lv_obj_set_style_text_color(ui_SoundIntensitySliderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SoundIntensitySliderLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);

}
