// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUNDBLUE 0
#define UI_THEME_COLOR_BACKGROUNDGREEN 1
#define UI_THEME_COLOR_FUNCTIONCLICKBTN 2

#define UI_THEME_DEFAULT 0

#define UI_THEME_BLUETHEME 1

#define UI_THEME_GREENTHEME 2

extern const ui_theme_variable_t _ui_theme_color_BackgroundBlue[3];
extern const ui_theme_variable_t _ui_theme_alpha_BackgroundBlue[3];

extern const ui_theme_variable_t _ui_theme_color_BackgroundGreen[3];
extern const ui_theme_variable_t _ui_theme_alpha_BackgroundGreen[3];

extern const ui_theme_variable_t _ui_theme_color_FunctionClickBtn[3];
extern const ui_theme_variable_t _ui_theme_alpha_FunctionClickBtn[3];

extern const uint32_t* ui_theme_colors[3];
extern const uint8_t* ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
