// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_BackgroundBlue[3] = {0x8B99BD, 0x8B99BD, 0x8B99BD};
const ui_theme_variable_t _ui_theme_alpha_BackgroundBlue[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_BackgroundGreen[3] = {0xA7E6BC, 0xA7E6BC, 0xA7E6BC};
const ui_theme_variable_t _ui_theme_alpha_BackgroundGreen[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_FunctionClickBtn[3] = {0xF3E1A8, 0xF3E1A8, 0xF3E1A8};
const ui_theme_variable_t _ui_theme_alpha_FunctionClickBtn[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

